<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-RV6F1IE" failures="1" tests="11" name="Test" time="41.504" errors="0" timestamp="2023-01-07T22:07:30 IST">
  <testcase classname="clientapp.tests.JsonDataTest" name="submitOrder4" time="0.0">
    <skipped/>
  </testcase> <!-- submitOrder4 -->
  <testcase classname="clientapp.tests.JsonDataTestByListeners" name="submitOrder5" time="0.0">
    <skipped/>
  </testcase> <!-- submitOrder5 -->
  <testcase classname="clientapp.tests.ErrorValidationsTest" name="LoginErrorValidation" time="3.059"/>
  <testcase classname="clientapp.tests.DataProviderTest" name="DataProviderTestDepends" time="6.524"/>
  <testcase classname="clientapp.tests.ClientAppTest" name="submitOrder1" time="5.911"/>
  <testcase classname="clientapp.tests.ErrorValidationsTest" name="ProductErrorValidation" time="3.414"/>
  <testcase classname="clientapp.tests.HashMapTest" name="submitOrder3" time="17.288">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at clientapp.tests.HashMapTest.submitOrder3(HashMapTest.java:28)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- submitOrder3 -->
  <testcase classname="clientapp.tests.ClientAppTest" name="orderHistoryTest" time="1.93"/>
  <testcase classname="clientapp.tests.DataProviderTest" name="submitOrder2" time="5.406"/>
  <testcase classname="clientapp.tests.HashMapTest" name="submitOrder3" time="4.056"/>
  <testcase classname="clientapp.tests.DataProviderTest" name="submitOrder2" time="3.656"/>
</testsuite> <!-- Test -->
